project_id = "vjatuupiufxyvprztmke"

[functions.n8n-proxy]
verify_jwt = false

[functions.status-callback]
verify_jwt = false

[functions.variate-message]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.evolution-groups]
verify_jwt = false
